imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['haml','twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

mt_haml:

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    form:
        resources:
            - "Edge5AppBackendBundle::fields.html.twig"
            - "AdmingeneratorGeneratorBundle:Form:fields.html.twig"
            - "AvocodeFormExtensionsBundle:Form:form_widgets.html.twig"
            - "AvocodeFormExtensionsBundle:Form:form_stylesheets.html.twig"
            - "AvocodeFormExtensionsBundle:Form:form_javascripts.html.twig"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: %uglify_js_path%
        uglifycss:
            bin: %uglify_css_path%
        sass:
            bin: /usr/bin/sass
        compass:
            bin: %compass_bin%
        edgefivecompass:
            resource: %kernel.root_dir%/../vendor/edge5/app-backend-bundle/Edge5/AppBackendBundle/Resources/config/edgefivecompass.xml
            bin: %compass_bin%
            config_files:
#                colors: %kernel.root_dir%/../src/Edge5/BackendBundle/Resources/public/scss/colors.scss
#                constants: %kernel.root_dir%/../vendor/edge5/app-backend-bundle/Edge5/AppBackendBundle/Resources/public/scss/constants.scss
#                custom: %kernel.root_dir%/../vendor/edge5/app-backend-bundle/Edge5/AppBackendBundle/Resources/public/scss/custom.scss

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Mobile Detect Configuration
mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~


fos_user:
    service:
        mailer: fos_user.mailer.noop
    db_driver: propel
    user_class: FOS\UserBundle\Propel\User
    firewall_name: main

admingenerator_generator:
    base_admin_template: Edge5BackendBundle::base_admin.html.twig
    dashboard_welcome_path: dashboard

    templates_dirs: ['%kernel.root_dir%/../vendor/edge5/app-backend-bundle/Edge5/AppBackendBundle/Resources/templates']

    use_doctrine_orm: false
    use_doctrine_odm: false
    use_propel: true

    login_path: startAdmin
    logout_path: fos_user_security_logout

    stylesheets: ~
    javascripts:
        - { path: bundles/edge5appbackend/js/backend.js }

admingenerator_user:
    login_template: Edge5BackendBundle::base_admin.html.twig

propel:
    path:       "%kernel.root_dir%/../vendor/propel/propel1"
    phing_path: "%kernel.root_dir%/../vendor/pear-phing"
    dbal:
        driver:               mysql
        user:                 %database_user%
        password:             %database_password%
        dsn:                  mysql:host=%database_host%;dbname=%database_name%;charset=UTF8
        options:              {}
        attributes:           {}

knp_menu:
    twig:
        template: AdmingeneratorGeneratorBundle:KnpMenu:knp_menu_trans.html.twig

jms_security_extra:
    expressions: true

edge5_app_backend:
    dashboard_template: Edge5BackendBundle::base_dashboard.html.twig

liip_imagine:
    filter_sets:
        # Edge5 AppBackendBundle filter sets
        preview_picture:
            quality: 90
            filters:
                thumbnail: { size: [80, 80], mode: inset }
        preview_medium:
            quality: 90
            filters:
                thumbnail: { size: [320, 250], mode: outbound }
        preview_large:
            quality: 90
            filters:
                thumbnail: { size: [640, 500], mode: outbound }
        edit_picture:
            quality: 90
            filters:
                thumbnail: { size: [360, 270], mode: outbound }

        # Project filter sets
        opengraph:
            quality: 90
            filters:
                thumbnail: { size: [600, 600], mode: inset }